name: Bug report
description: Report a bug in Decentraland
labels: [new, explorer]
body:

- type: markdown
  attributes:
    value: |
      Thank you for taking the time to report this issue! Before reporting, please be sure to check the open [issues](https://github.com/decentraland/issues) to ensure it's already reported by someone else.
  
- type: dropdown
  id: browser
  attributes:
    label: What browsers are you seeing the problem on?
    options:
      - Firefox
      - Chrome
      - Microsoft Edge
      - Safari
      - Opera
      - Other
  validations:
    required: true

- type: dropdown
  id: os
  attributes:
    label: What is your operating system?
    options:
      - Windows
      - MacOS
      - Linux
      - Other
  validations: 
    required: true

- type: dropdown
  id: wallet
  attributes:
    label: Which wallet are you using?
    options:
      - Metamask
      - Fortmatic
      - Wallet Connect
      - None, played as guest
  validations: 
    required: true

- type: input
  id: sysinfo
  attributes:
    label: System information
    description: |
      Describe the technical specifications of your device, including CPU, graphics card and memory.
    placeholder: Intel i9 10th generation, 32GB RAM, NVIDIA 980TI
  validations:
    required: true

- type: input
  id: kernel
  attributes:
    label: Kernel Version
    description: >
        If this field is not filled automatically, please run the /version command in the chat window to see the kernel and unity renderer versions.
    placeholder: latest
  validations:
    required: false

- type: input
  id: unity
  attributes:
    label: Unity Version
    description: >
        If this field is not filled automatically, please run the /version command in the chat window to see the kernel and unity renderer versions.
    placeholder: latest
  validations:
    required: false

- type: input
  id: realm
  attributes:
    label: In which realm are you?
    placeholder: 
  validations:
    required: false

- type: input
  id: nametag
  attributes:
    label: What's your in-game nametag?
    placeholder: johndoe#1111
  validations:
    required: false

- type: textarea
  attributes:
    label: What happened?
    description: |
      Please try to describe in detail what your issue has been. 
      You can include screenshots or videos by simply dragging and dropping them into this field, or include portions of code using the <code>```</code> tags.
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: |
      Describe the necessary steps we can take in order to reproduce this error.
  validations:
    required: true
