name: slack-notification

on: [issues]

jobs:
  slack-notification:
    runs-on: windows-2019
    name: Send Message

    steps:
      - name: Send Slack Message
        uses: archive/github-actions-slack@master
        id: send-message
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C02E2GKP0UA
          slack-text: New issue reported and Repo "${{ github.repository }}"

      - name: Result from "Send Slack Message"
        run: echo '${{ steps.send-message.outputs.slack-result }}'
